<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search for_custom-logo</name>
   <tag></tag>
   <elementGuidId>1bdce8e1-b99f-412b-af51-086d9c94cad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='masthead']/div/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.custom-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#masthead >> internal:role=link[name=&quot;VKP Press &amp; News&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0335c1f8-66aa-4ad9-b52b-044f80e3d749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1272</value>
      <webElementGuid>d96f50ea-f9af-4e94-a48b-aa56df3134e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>995</value>
      <webElementGuid>8e61c7a5-2235-424e-831c-8f8279c87b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://press.vkp.co.in/wp-content/uploads/2020/06/cropped-logo2.png</value>
      <webElementGuid>7920ccf7-a8cb-4fa4-ae77-fe8e4058b678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-logo</value>
      <webElementGuid>870b3f1b-fde1-4cf8-aee7-42d1d0798b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>VKP Press &amp; News</value>
      <webElementGuid>a4c55df2-dce1-4ac4-888d-2d2260615de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://press.vkp.co.in/wp-content/uploads/2020/06/cropped-logo2.png 1272w, https://press.vkp.co.in/wp-content/uploads/2020/06/cropped-logo2-300x235.png 300w, https://press.vkp.co.in/wp-content/uploads/2020/06/cropped-logo2-1024x801.png 1024w, https://press.vkp.co.in/wp-content/uploads/2020/06/cropped-logo2-768x601.png 768w</value>
      <webElementGuid>be1a3dbb-1ab1-4aaa-a271-0dc369ae39e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1272px) 100vw, 1272px</value>
      <webElementGuid>a918109d-27d7-4289-ba21-9c215d7569ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masthead&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-lg-3 col-7&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;site-logo&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;custom-logo&quot;]</value>
      <webElementGuid>49c3f9ff-49fa-4962-8864-9af3d462ec35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='masthead']/div/div/div/div/div/a/img</value>
      <webElementGuid>49e237d0-1fde-4ec7-af72-fcace686313d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='VKP Press &amp; News']</value>
      <webElementGuid>4b5050d2-e6f0-4102-b696-1fcc0b363265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0cf0a70d-7d4d-49a0-904b-1942d21628a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://press.vkp.co.in/wp-content/uploads/2020/06/cropped-logo2.png' and @alt = 'VKP Press &amp; News']</value>
      <webElementGuid>cc9ce556-96bb-4de8-b7a9-8d28d9ecad7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
