<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enquiry</name>
   <tag></tag>
   <elementGuidId>c39ad721-f30c-4539-b319-633910d587c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Enquiry')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.enq-fixed > a[title=&quot;Enquiry&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Enquiry&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71d072a5-7ccf-4e8c-a752-9cded6409aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://enquiry.vkpschools.com/</value>
      <webElementGuid>e6b4a899-d55c-4a67-b17d-9d1c4e8c6a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enquiry</value>
      <webElementGuid>9f701fae-a091-4b49-9d79-5b6bdfc8f8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>025dc252-e49a-4e2c-b04d-0e8d84f17286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Enquiry</value>
      <webElementGuid>b787a153-58aa-435e-b695-f05dee6ca148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;enq-fixed&quot;]/a[1]</value>
      <webElementGuid>62f7f4ae-c731-4973-b39e-479425bb20da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Enquiry')])[2]</value>
      <webElementGuid>0b7a7044-c0fb-4b5a-96b4-7de4db239372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NexBorg'])[1]/following::a[1]</value>
      <webElementGuid>6e8fdacb-e39b-4860-8356-b6a1590a97d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reach us:'])[1]/following::a[2]</value>
      <webElementGuid>3322b536-0677-41c7-889b-96a55b873b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://enquiry.vkpschools.com/'])[2]</value>
      <webElementGuid>20e566a2-ce08-47a3-ae20-b10e535cbb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>3b32edff-3f3b-4e01-a073-be0de6a9a20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://enquiry.vkpschools.com/' and @title = 'Enquiry' and (text() = ' Enquiry' or . = ' Enquiry')]</value>
      <webElementGuid>c8bc2411-8d28-42ae-ab4d-e1a21ee53c59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
