<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admission open20</name>
   <tag></tag>
   <elementGuidId>18ccfec8-8183-4867-b8d2-f38e29e62ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-555']/div[2]/header/h2/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#post-555 > div.sy-card__content.p-4 > header.entry-header > h2.entry-title > a.transition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Admission open’20&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d00b0206-1596-4a69-96a1-b3617cc9eeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition</value>
      <webElementGuid>82cd6b02-8c64-4a31-ad6f-6a1a55a36129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://blog.vkp.co.in/index.php/2020/06/24/admission-open20/</value>
      <webElementGuid>18072d5c-f419-4bb6-8e58-930f55eae78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>bookmark</value>
      <webElementGuid>26fbf4a7-e17b-4ea2-9ef0-502359d4e656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admission open’20</value>
      <webElementGuid>fad5783f-7b4a-4907-bc03-3121761ee483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-555&quot;)/div[@class=&quot;sy-card__content p-4&quot;]/header[@class=&quot;entry-header&quot;]/h2[@class=&quot;entry-title&quot;]/a[@class=&quot;transition&quot;]</value>
      <webElementGuid>cb4a1f04-04f8-4c01-bb24-f3867bb72b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-555']/div[2]/header/h2/a[2]</value>
      <webElementGuid>f0f132ce-0333-40f1-9f0b-e5627b9e66d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admission open’20')]</value>
      <webElementGuid>b65074cb-c643-40d6-af8a-39d6ab3c1e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 24, 2020'])[2]/following::a[4]</value>
      <webElementGuid>33e9e708-8dc4-4e93-855f-432262ac6223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 24, 2020'])[1]/following::a[4]</value>
      <webElementGuid>2d525ff4-cae4-4dad-bb3c-6ea3a572cd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vkpadmin'])[3]/preceding::a[1]</value>
      <webElementGuid>4bd4f89c-bb0d-441f-9cf7-f8a93b749c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admission open’20']/parent::*</value>
      <webElementGuid>414b9eab-8182-46b3-bc1a-ce5dfc8fbb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://blog.vkp.co.in/index.php/2020/06/24/admission-open20/')]</value>
      <webElementGuid>dc1edb08-0924-4588-b124-8adc5b1fd9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/article/div[2]/header/h2/a[2]</value>
      <webElementGuid>f2915bb0-a0d3-4e44-ba62-43ff47cf0f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://blog.vkp.co.in/index.php/2020/06/24/admission-open20/' and (text() = 'Admission open’20' or . = 'Admission open’20')]</value>
      <webElementGuid>ce008616-1082-4fa2-91a9-b9392539b14b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
