<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Velammal Knowledge Park_1</name>
   <tag></tag>
   <elementGuidId>810d8dfb-f083-405e-ae7e-4bfcb70bd0d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-535']/div[2]/header/h2/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#post-535 > div.sy-card__content.p-4 > header.entry-header > h2.entry-title > a.transition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#post-535 >> internal:role=link[name=&quot;Velammal Knowledge Park&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>298115da-b43e-427f-a6ee-72918ea6a3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition</value>
      <webElementGuid>bef2ce31-7857-40ec-8832-0bb941253c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://blog.vkp.co.in/index.php/2020/06/24/535/</value>
      <webElementGuid>743e2c88-2fa1-4c93-8b08-00847b8becac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>bookmark</value>
      <webElementGuid>9bce2c76-260b-43f4-8133-e67662c49c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Velammal Knowledge Park</value>
      <webElementGuid>ccc8a378-b144-4597-87e2-8c3c9b9c78bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-535&quot;)/div[@class=&quot;sy-card__content p-4&quot;]/header[@class=&quot;entry-header&quot;]/h2[@class=&quot;entry-title&quot;]/a[@class=&quot;transition&quot;]</value>
      <webElementGuid>86079f93-b414-42eb-9b49-d3ceb46d47c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-535']/div[2]/header/h2/a[2]</value>
      <webElementGuid>222650ef-aebc-415b-9195-f9db641ee45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Velammal Knowledge Park')])[2]</value>
      <webElementGuid>10debe74-b9b9-4112-bcb0-b530618abe0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 24, 2020'])[13]/following::a[4]</value>
      <webElementGuid>7b283632-4ea0-477b-9a6a-d7fd43716619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 24, 2020'])[12]/following::a[4]</value>
      <webElementGuid>baefd893-3072-4448-9ec0-777dddb62d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vkpadmin'])[9]/preceding::a[1]</value>
      <webElementGuid>3aae9271-bba9-4935-b27e-4ca1b9be8871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://blog.vkp.co.in/index.php/2020/06/24/535/')]</value>
      <webElementGuid>f16f31ab-ab05-41cc-98c8-51d05cee2742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/article/div[2]/header/h2/a[2]</value>
      <webElementGuid>12244fd3-e4f7-48a1-836d-e764aa64c184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://blog.vkp.co.in/index.php/2020/06/24/535/' and (text() = 'Velammal Knowledge Park' or . = 'Velammal Knowledge Park')]</value>
      <webElementGuid>420b5df7-0160-49c0-9b24-7258bbd68ae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
