<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Benefits</name>
   <tag></tag>
   <elementGuidId>befc3de3-c2d4-4c1d-81d4-383d270efbff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/header/div/div/div[2]/nav/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.sc-19t5w3d-2.inosqo > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Benefits&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48da9e8f-fea4-4a32-aae3-4c389c0d4c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Benefits</value>
      <webElementGuid>e9e66d0a-3116-40da-a18a-d629bd6edaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pageurl</name>
      <type>Main</type>
      <value>/corporate-expense-management</value>
      <webElementGuid>004e2acd-8789-4d3e-ad6b-436689f31d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackval</name>
      <type>Main</type>
      <value>benefits_clicked</value>
      <webElementGuid>03564e60-fe3d-421c-a2f9-869af682f5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>Benefits</value>
      <webElementGuid>af297c54-591f-4956-ae27-7aaa1132c0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benefits</value>
      <webElementGuid>fe31ede9-45a6-4107-ac74-7ecc570c11f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;sc-19t5w3d-0 bRSoTG&quot;]/div[@class=&quot;sc-1nwjbkl-1 dujXYk&quot;]/div[@class=&quot;sc-19t5w3d-1 isNLtr&quot;]/div[@class=&quot;sc-1nwjbkl-3 sc-1nwjbkl-7 kmqemK khHzFU&quot;]/nav[@class=&quot;sc-19t5w3d-2 inosqo&quot;]/a[1]</value>
      <webElementGuid>26f0d3df-9125-424b-9850-e24465bcd379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div/div/div[2]/nav/a</value>
      <webElementGuid>ee180e54-5ca6-4b44-bd6c-06664f8a2401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Benefits')]</value>
      <webElementGuid>77e255d9-0f71-41b3-a631-1b03a09ba9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By MakeMyTrip'])[1]/following::a[1]</value>
      <webElementGuid>a8a54938-ae9a-44ee-bb48-84cfe4a82a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/preceding::a[1]</value>
      <webElementGuid>d0f24340-0bae-48fa-8db2-58358700cdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN IN / SIGN UP'])[1]/preceding::a[2]</value>
      <webElementGuid>10d034cf-8e6a-4e41-af30-af0c76a626f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Benefits']/parent::*</value>
      <webElementGuid>93618a10-d481-4a87-87b8-da3bc77e8c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Benefits')]</value>
      <webElementGuid>84bc8871-9599-40c2-859f-2b7559b3f7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a</value>
      <webElementGuid>dd048add-e374-4fa0-8659-0615d6dda5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Benefits' and (text() = 'Benefits' or . = 'Benefits')]</value>
      <webElementGuid>746a06e5-05d5-48e2-b7fb-bf321cef9b36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
