<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_11th Graduation Day  Live in YouTube</name>
   <tag></tag>
   <elementGuidId>5c2ac2ff-d001-41a2-8e31-4ac827989228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='vertical-ticker']/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;11th Graduation Day – Live in YouTube&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;11th Graduation Day – Live in YouTube&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>014b06e3-fb79-4ec2-b5cf-573d080ebec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://velammalitech.edu.in/11th-graduation-day-live-in-youtube/</value>
      <webElementGuid>7367ac41-3b4f-4185-b82f-275e2e7582e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>6d60557f-6f5c-4a92-9d3f-53375f140428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>11th Graduation Day – Live in YouTube</value>
      <webElementGuid>8d4f577d-314b-45d7-abb7-546f39a6d193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11th Graduation Day – Live in YouTube</value>
      <webElementGuid>504d2f85-27bd-45f6-b05a-88c4a07980dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campus_news&quot;)/div[@class=&quot;panel-body&quot;]/ul[@id=&quot;vertical-ticker&quot;]/li[3]/a[1]</value>
      <webElementGuid>01884880-e740-4193-8a93-2c12be4567a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vertical-ticker']/li[3]/a</value>
      <webElementGuid>2b7e5c6b-8b4f-4b9a-b1c6-e8c9da1e209b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'11th Graduation Day – Live in YouTube')]</value>
      <webElementGuid>266ed6d0-b04e-4f6b-b3de-70d30a4432e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT &amp; ECE has signed MOU for collaboration with Amizhth Techno Solutions Private Limited'])[1]/following::a[2]</value>
      <webElementGuid>df8ed083-ad8a-4c32-a6b9-6e27674e386b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campus News'])[1]/following::a[3]</value>
      <webElementGuid>abd4262b-6830-434a-916d-c1e429c9d530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Innovate 24'])[1]/preceding::a[2]</value>
      <webElementGuid>ce7d24ab-8aff-45f3-98b7-5e46c44d7a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='International Conference – ICDAIC ’24 by AI&amp;DS'])[1]/preceding::a[3]</value>
      <webElementGuid>2a554ab5-1ee2-4df6-b9d0-96922c6351ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11th Graduation Day – Live in YouTube']/parent::*</value>
      <webElementGuid>c3ddfc75-305d-4311-8eb3-ce17176cbc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://velammalitech.edu.in/11th-graduation-day-live-in-youtube/')]</value>
      <webElementGuid>3c4f38cf-8ee1-4d45-a843-57cc6f571d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/ul/li[3]/a</value>
      <webElementGuid>aaa72a84-b06d-43a0-a048-49ee2b2320e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://velammalitech.edu.in/11th-graduation-day-live-in-youtube/' and @title = '11th Graduation Day – Live in YouTube' and (text() = '11th Graduation Day – Live in YouTube' or . = '11th Graduation Day – Live in YouTube')]</value>
      <webElementGuid>196d9746-ada4-41f7-a771-eee345091144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
