<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Kolapakkam</name>
   <tag></tag>
   <elementGuidId>5bb8d455-27b2-4a48-a4a4-994ecc57b29f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='ab-home']/div[3]/div/div[2]/div/div/div[2]/div/div/div[2]/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Kolapakkam&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>777fb644-671a-49a9-bd3f-1266ca7f4e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kolapakkam</value>
      <webElementGuid>43f0cce9-474a-4f59-b1c5-68269b67e4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab-home&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 schoolinner-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;col-sm-12 inside&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 right&quot;]/div[@class=&quot;inner&quot;]/h3[1]</value>
      <webElementGuid>b4419675-9866-492d-a48b-6ac6324e5c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ab-home']/div[3]/div/div[2]/div/div/div[2]/div/div/div[2]/div/h3</value>
      <webElementGuid>f463fce0-b038-4237-b7ea-6ed6c940d2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='visit website'])[1]/following::h3[1]</value>
      <webElementGuid>76209fdc-8308-4f1e-b6d4-257e77d36f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Velammal International School Kolkatta High Road Panchetti - 601 204 Tamil Nadu, India'])[1]/following::h3[1]</value>
      <webElementGuid>13505954-d5b9-4fd7-ad52-1073fe88ff8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AV Garden Jayapriya nagar, Kolapakkam, porur, chennai 600128'])[1]/preceding::h3[1]</value>
      <webElementGuid>3f59913f-573d-4492-b497-b9fe009891cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kolapakkam']/parent::*</value>
      <webElementGuid>25ef5c50-9a36-41b2-98b0-deadcaf7ee73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/h3</value>
      <webElementGuid>eb991177-6f3e-4c4b-a548-6cdbed0fe61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Kolapakkam' or . = 'Kolapakkam')]</value>
      <webElementGuid>82d51767-b182-47fc-b5a7-ffdcdc117987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
