<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_VelammalMatriculationSchools_wp-image-536</name>
   <tag></tag>
   <elementGuidId>f7184e6a-1a06-4270-ae70-8c16b1f27ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-535']/div[2]/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-536</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#post-535 img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65fb0076-50e3-4c56-85e1-74576e1030ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://blog.vkp.co.in/wp-content/uploads/2020/06/0.jpg</value>
      <webElementGuid>2543e7b8-7523-4701-bdec-a034237167dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-536</value>
      <webElementGuid>de8cf2bb-1213-4d30-a0b5-d84a46da9500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://blog.vkp.co.in/wp-content/uploads/2020/06/0.jpg 800w, https://blog.vkp.co.in/wp-content/uploads/2020/06/0-300x212.jpg 300w, https://blog.vkp.co.in/wp-content/uploads/2020/06/0-768x542.jpg 768w</value>
      <webElementGuid>dd43c5ce-0630-4f35-999f-fea09dc13059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 800px) 100vw, 800px</value>
      <webElementGuid>ebd302a8-134f-456d-8b21-b5c82ef13016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-535&quot;)/div[@class=&quot;entry-content&quot;]/figure[@class=&quot;wp-block-image size-large&quot;]/img[@class=&quot;wp-image-536&quot;]</value>
      <webElementGuid>92ac59c8-6eaa-4908-9397-f083dd992e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-535']/div[2]/figure/img</value>
      <webElementGuid>dc616bca-7c91-4c99-9a66-ac003677d05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://blog.vkp.co.in/wp-content/uploads/2020/06/0.jpg')]</value>
      <webElementGuid>0793ff88-2cee-4f83-bf3b-3d7569261e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>8dc988da-b0f3-4eb1-9640-bf3ef7fbc6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://blog.vkp.co.in/wp-content/uploads/2020/06/0.jpg']</value>
      <webElementGuid>b29b21d0-de21-48e6-a3e5-167acf524a44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
