<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_vbaonline.in_namemaster-1,slave-1-1c_13b713</name>
   <tag></tag>
   <elementGuidId>6cbbc196-211e-4ae8-a8c2-4ac7176a5490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='master-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#master-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;\{\&quot;name\&quot;\:\&quot;master-1\&quot;\,\&quot;slave-1-1\&quot;\:\{\&quot;clicktrackUrl\&quot;\:\&quot;https\:\/\/vbaonline\.in\/track\.php\?click\=caf\&amp;domain\=vbaonline\.in\&amp;uid\=MTcxODM1NTAxMy42MjQzOjRhNjE0ODFmODhjOGMzZDJmYWVlNzI1ZTVhYTllNWM5MDNmNGRmNTY0ODdhYTRjY2EyM2E2MTI0NTcwYmEwNzY6NjY2YzA0NDU5ODZhOQ\%3D\%3D\&amp;ts\=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OHxmMDkxYjFhNDU3NjFmY2ViNWE1MTZhYWJkMzA2NTE2NGI2MGVkYzUwfHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8\&amp;adtest\=off\&quot;\,\&quot;container\&quot;\:\&quot;search\&quot;\,\&quot;styleId\&quot;\:7840396037\,\&quot;personalizedAds\&quot;\:false\,\&quot;channel\&quot;\:\&quot;000001\,bucket011\,bucket077\&quot;\,\&quot;domainName\&quot;\:\&quot;vbaonline\.in\&quot;\,\&quot;fexp\&quot;\:\&quot;21404\,17301431\,17301433\,17301436\,17301511\,17301516\,17301266\&quot;\,\&quot;masterNumber\&quot;\:1\,\&quot;number\&quot;\:10\,\&quot;pubId\&quot;\:\&quot;dp-mobile-teaminternet13_3ph\&quot;\,\&quot;role\&quot;\:\&quot;s\&quot;\,\&quot;slaveNumber\&quot;\:1\,\&quot;hl\&quot;\:\&quot;en\&quot;\,\&quot;client_gdprApplies\&quot;\:0\,\&quot;colorAttribution\&quot;\:\&quot;\#b7b7b7\&quot;\,\&quot;fontFamily\&quot;\:\&quot;arial\&quot;\,\&quot;fontFamilyAttribution\&quot;\:\&quot;arial\&quot;\,\&quot;rolloverLinkBold\&quot;\:false\,\&quot;resultsPageBaseUrl\&quot;\:\&quot;https\:\/\/vbaonline\.in\/\?ts\=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OXxjNDk0NWE3YTZmYzJjMDgwNWJlZTEyODEzM2IxNzY4OTcxODQyYTE2fHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8\&quot;\,\&quot;columns\&quot;\:1\,\&quot;horizontalAlignment\&quot;\:\&quot;left\&quot;\,\&quot;resultsPageQueryParam\&quot;\:\&quot;query\&quot;\,\&quot;terms\&quot;\:\&quot;\&quot;\,\&quot;kw\&quot;\:\&quot;\&quot;\,\&quot;ie\&quot;\:\&quot;UTF-8\&quot;\,\&quot;maxTermLength\&quot;\:40\,\&quot;maxTop\&quot;\:null\,\&quot;minTop\&quot;\:null\,\&quot;oe\&quot;\:\&quot;UTF-8\&quot;\,\&quot;type\&quot;\:\&quot;searchbox\&quot;\,\&quot;linkTarget\&quot;\:\&quot;_blank\&quot;\,\&quot;fontSizeTitle\&quot;\:18\,\&quot;fontSizeAttribution\&quot;\:\&quot;16px\&quot;\,\&quot;colorBackground\&quot;\:\&quot;transparent\&quot;\,\&quot;hideSearchInputBorder\&quot;\:false\,\&quot;hideSearchButtonBorder\&quot;\:true\,\&quot;colorSearchButton\&quot;\:\&quot;\#0b3279\&quot;\,\&quot;colorSearchButtonText\&quot;\:\&quot;\#fff\&quot;\,\&quot;fontSizeSearchInput\&quot;\:12\,\&quot;fontSizeSearchButton\&quot;\:13\,\&quot;attributionBold\&quot;\:false\,\&quot;uiOptimize\&quot;\:true\,\&quot;domainRegistrant\&quot;\:\&quot;as-drid-2558334540730768\&quot;\}\,\&quot;master-1\&quot;\:\{\&quot;clicktrackUrl\&quot;\:\&quot;https\:\/\/vbaonline\.in\/track\.php\?click\=caf\&amp;domain\=vbaonline\.in\&amp;uid\=MTcxODM1NTAxMy42MjQzOjRhNjE0ODFmODhjOGMzZDJmYWVlNzI1ZTVhYTllNWM5MDNmNGRmNTY0ODdhYTRjY2EyM2E2MTI0NTcwYmEwNzY6NjY2YzA0NDU5ODZhOQ\%3D\%3D\&amp;ts\=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OHxmMDkxYjFhNDU3NjFmY2ViNWE1MTZhYWJkMzA2NTE2NGI2MGVkYzUwfHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8\&amp;adtest\=off\&quot;\,\&quot;container\&quot;\:\&quot;tc\&quot;\,\&quot;styleId\&quot;\:7840396037\,\&quot;personalizedAds\&quot;\:false\,\&quot;channel\&quot;\:\&quot;000001\,bucket011\,bucket077\&quot;\,\&quot;domainName\&quot;\:\&quot;vbaonline\.in\&quot;\,\&quot;fexp\&quot;\:\&quot;21404\,17301431\,17301433\,17301436\,17301511\,17301516\,17301266\&quot;\,\&quot;masterNumber\&quot;\:1\,\&quot;number\&quot;\:3\,\&quot;pubId\&quot;\:\&quot;dp-mobile-teaminternet13_3ph\&quot;\,\&quot;role\&quot;\:\&quot;m\&quot;\,\&quot;hl\&quot;\:\&quot;en\&quot;\,\&quot;client_gdprApplies\&quot;\:0\,\&quot;colorTitleLink\&quot;\:\&quot;\#0277bd\&quot;\,\&quot;colorAttribution\&quot;\:\&quot;\#aaa\&quot;\,\&quot;fontFamily\&quot;\:\&quot;arial\&quot;\,\&quot;fontFamilyAttribution\&quot;\:\&quot;arial\&quot;\,\&quot;rolloverLinkBold\&quot;\:false\,\&quot;rolloverLinkColor\&quot;\:\&quot;\#01579b\&quot;\,\&quot;noTitleUnderline\&quot;\:false\,\&quot;lineHeightTitle\&quot;\:34\,\&quot;resultsPageBaseUrl\&quot;\:\&quot;https\:\/\/vbaonline\.in\/\?ts\=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OXxjNDk0NWE3YTZmYzJjMDgwNWJlZTEyODEzM2IxNzY4OTcxODQyYTE2fHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8\&quot;\,\&quot;columns\&quot;\:1\,\&quot;horizontalAlignment\&quot;\:\&quot;center\&quot;\,\&quot;resultsPageQueryParam\&quot;\:\&quot;query\&quot;\,\&quot;terms\&quot;\:\&quot;\&quot;\,\&quot;kw\&quot;\:\&quot;\&quot;\,\&quot;ie\&quot;\:\&quot;UTF-8\&quot;\,\&quot;maxTermLength\&quot;\:40\,\&quot;maxTop\&quot;\:null\,\&quot;minTop\&quot;\:null\,\&quot;oe\&quot;\:\&quot;UTF-8\&quot;\,\&quot;type\&quot;\:\&quot;relatedsearch\&quot;\,\&quot;linkTarget\&quot;\:\&quot;_blank\&quot;\,\&quot;verticalSpacing\&quot;\:10\,\&quot;fontSizeTitle\&quot;\:\&quot;24px\&quot;\,\&quot;fontSizeAttribution\&quot;\:\&quot;14px\&quot;\,\&quot;colorBackground\&quot;\:\&quot;transparent\&quot;\,\&quot;attributionBold\&quot;\:false\,\&quot;uiOptimize\&quot;\:true\,\&quot;domainRegistrant\&quot;\:\&quot;as-drid-2558334540730768\&quot;\}\}&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>28278c41-39c4-4e44-9f2e-9b6f37010b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>768cf1b8-9b0e-46bc-8d16-3fbfc40c68be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>76b5513c-06ed-4d20-91a7-ff399c55e821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>32d49010-f2c9-42fe-8979-4e4a5862bd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac8fe080-8d67-46e0-8f87-00b0cf0cb3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0ed85169-eef7-4465-ac53-fe37c5930ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c868a4ce-6a6c-4e47-91ca-260747888251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>{&quot;name&quot;:&quot;master-1&quot;,&quot;slave-1-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://vbaonline.in/track.php?click=caf&amp;domain=vbaonline.in&amp;uid=MTcxODM1NTAxMy42MjQzOjRhNjE0ODFmODhjOGMzZDJmYWVlNzI1ZTVhYTllNWM5MDNmNGRmNTY0ODdhYTRjY2EyM2E2MTI0NTcwYmEwNzY6NjY2YzA0NDU5ODZhOQ%3D%3D&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OHxmMDkxYjFhNDU3NjFmY2ViNWE1MTZhYWJkMzA2NTE2NGI2MGVkYzUwfHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&amp;adtest=off&quot;,&quot;container&quot;:&quot;search&quot;,&quot;styleId&quot;:7840396037,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011,bucket077&quot;,&quot;domainName&quot;:&quot;vbaonline.in&quot;,&quot;fexp&quot;:&quot;21404,17301431,17301433,17301436,17301511,17301516,17301266&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:10,&quot;pubId&quot;:&quot;dp-mobile-teaminternet13_3ph&quot;,&quot;role&quot;:&quot;s&quot;,&quot;slaveNumber&quot;:1,&quot;hl&quot;:&quot;en&quot;,&quot;client_gdprApplies&quot;:0,&quot;colorAttribution&quot;:&quot;#b7b7b7&quot;,&quot;fontFamily&quot;:&quot;arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;rolloverLinkBold&quot;:false,&quot;resultsPageBaseUrl&quot;:&quot;https://vbaonline.in/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OXxjNDk0NWE3YTZmYzJjMDgwNWJlZTEyODEzM2IxNzY4OTcxODQyYTE2fHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;&quot;,&quot;kw&quot;:&quot;&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;searchbox&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;fontSizeTitle&quot;:18,&quot;fontSizeAttribution&quot;:&quot;16px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;hideSearchInputBorder&quot;:false,&quot;hideSearchButtonBorder&quot;:true,&quot;colorSearchButton&quot;:&quot;#0b3279&quot;,&quot;colorSearchButtonText&quot;:&quot;#fff&quot;,&quot;fontSizeSearchInput&quot;:12,&quot;fontSizeSearchButton&quot;:13,&quot;attributionBold&quot;:false,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2558334540730768&quot;},&quot;master-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://vbaonline.in/track.php?click=caf&amp;domain=vbaonline.in&amp;uid=MTcxODM1NTAxMy42MjQzOjRhNjE0ODFmODhjOGMzZDJmYWVlNzI1ZTVhYTllNWM5MDNmNGRmNTY0ODdhYTRjY2EyM2E2MTI0NTcwYmEwNzY6NjY2YzA0NDU5ODZhOQ%3D%3D&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OHxmMDkxYjFhNDU3NjFmY2ViNWE1MTZhYWJkMzA2NTE2NGI2MGVkYzUwfHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&amp;adtest=off&quot;,&quot;container&quot;:&quot;tc&quot;,&quot;styleId&quot;:7840396037,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011,bucket077&quot;,&quot;domainName&quot;:&quot;vbaonline.in&quot;,&quot;fexp&quot;:&quot;21404,17301431,17301433,17301436,17301511,17301516,17301266&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:3,&quot;pubId&quot;:&quot;dp-mobile-teaminternet13_3ph&quot;,&quot;role&quot;:&quot;m&quot;,&quot;hl&quot;:&quot;en&quot;,&quot;client_gdprApplies&quot;:0,&quot;colorTitleLink&quot;:&quot;#0277bd&quot;,&quot;colorAttribution&quot;:&quot;#aaa&quot;,&quot;fontFamily&quot;:&quot;arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;rolloverLinkBold&quot;:false,&quot;rolloverLinkColor&quot;:&quot;#01579b&quot;,&quot;noTitleUnderline&quot;:false,&quot;lineHeightTitle&quot;:34,&quot;resultsPageBaseUrl&quot;:&quot;https://vbaonline.in/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OXxjNDk0NWE3YTZmYzJjMDgwNWJlZTEyODEzM2IxNzY4OTcxODQyYTE2fHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;center&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;&quot;,&quot;kw&quot;:&quot;&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;relatedsearch&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;verticalSpacing&quot;:10,&quot;fontSizeTitle&quot;:&quot;24px&quot;,&quot;fontSizeAttribution&quot;:&quot;14px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;attributionBold&quot;:false,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2558334540730768&quot;}}</value>
      <webElementGuid>d4cd656d-6b2d-41ef-a2b7-117e9c777d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>master-1</value>
      <webElementGuid>d2bf44f3-a829-4533-b0f5-eae0cb88e237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://syndicatedsearch.goog/afs/ads?adtest=off&amp;psid=7840396037&amp;pcsa=false&amp;channel=000001%2Cbucket011%2Cbucket077&amp;client=dp-mobile-teaminternet13_3ph&amp;r=m&amp;hl=en&amp;rpbu=https%3A%2F%2Fvbaonline.in%2F%3Fts%3DfENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OXxjNDk0NWE3YTZmYzJjMDgwNWJlZTEyODEzM2IxNzY4OTcxODQyYTE2fHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&amp;max_radlink_len=40&amp;type=3&amp;uiopt=true&amp;swp=as-drid-2558334540730768&amp;oe=UTF-8&amp;ie=UTF-8&amp;fexp=21404%2C17301431%2C17301433%2C17301436%2C17301511%2C17301516%2C17301266&amp;client_gdprApplies=0&amp;format=r3%7Cs&amp;nocache=9931718355015159&amp;num=0&amp;output=afd_ads&amp;domain_name=vbaonline.in&amp;v=3&amp;bsl=8&amp;pac=0&amp;u_his=2&amp;u_tz=330&amp;dt=1718355015160&amp;u_w=1920&amp;u_h=1080&amp;biw=929&amp;bih=873&amp;psw=929&amp;psh=791&amp;frm=0&amp;uio=--&amp;cont=tc&amp;drt=0&amp;jsid=caf&amp;nfp=1&amp;jsv=641883529&amp;rurl=https%3A%2F%2Fvbaonline.in%2F</value>
      <webElementGuid>2cae93d2-9e23-4c0e-9d15-5b7c87ca5dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;master-1&quot;)</value>
      <webElementGuid>11d3cad0-bf9e-4ac8-a61a-4433b6623f25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='master-1']</value>
      <webElementGuid>631b641b-4672-4015-8f2a-eb16c52b06e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tc']/iframe</value>
      <webElementGuid>e532dd0d-908e-49f2-8d81-77b1a833150d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0644617f-8be2-4a26-9e0e-2b24070b725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '{&quot;name&quot;:&quot;master-1&quot;,&quot;slave-1-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://vbaonline.in/track.php?click=caf&amp;domain=vbaonline.in&amp;uid=MTcxODM1NTAxMy42MjQzOjRhNjE0ODFmODhjOGMzZDJmYWVlNzI1ZTVhYTllNWM5MDNmNGRmNTY0ODdhYTRjY2EyM2E2MTI0NTcwYmEwNzY6NjY2YzA0NDU5ODZhOQ%3D%3D&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OHxmMDkxYjFhNDU3NjFmY2ViNWE1MTZhYWJkMzA2NTE2NGI2MGVkYzUwfHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&amp;adtest=off&quot;,&quot;container&quot;:&quot;search&quot;,&quot;styleId&quot;:7840396037,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011,bucket077&quot;,&quot;domainName&quot;:&quot;vbaonline.in&quot;,&quot;fexp&quot;:&quot;21404,17301431,17301433,17301436,17301511,17301516,17301266&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:10,&quot;pubId&quot;:&quot;dp-mobile-teaminternet13_3ph&quot;,&quot;role&quot;:&quot;s&quot;,&quot;slaveNumber&quot;:1,&quot;hl&quot;:&quot;en&quot;,&quot;client_gdprApplies&quot;:0,&quot;colorAttribution&quot;:&quot;#b7b7b7&quot;,&quot;fontFamily&quot;:&quot;arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;rolloverLinkBold&quot;:false,&quot;resultsPageBaseUrl&quot;:&quot;https://vbaonline.in/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OXxjNDk0NWE3YTZmYzJjMDgwNWJlZTEyODEzM2IxNzY4OTcxODQyYTE2fHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;left&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;&quot;,&quot;kw&quot;:&quot;&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;searchbox&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;fontSizeTitle&quot;:18,&quot;fontSizeAttribution&quot;:&quot;16px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;hideSearchInputBorder&quot;:false,&quot;hideSearchButtonBorder&quot;:true,&quot;colorSearchButton&quot;:&quot;#0b3279&quot;,&quot;colorSearchButtonText&quot;:&quot;#fff&quot;,&quot;fontSizeSearchInput&quot;:12,&quot;fontSizeSearchButton&quot;:13,&quot;attributionBold&quot;:false,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2558334540730768&quot;},&quot;master-1&quot;:{&quot;clicktrackUrl&quot;:&quot;https://vbaonline.in/track.php?click=caf&amp;domain=vbaonline.in&amp;uid=MTcxODM1NTAxMy42MjQzOjRhNjE0ODFmODhjOGMzZDJmYWVlNzI1ZTVhYTllNWM5MDNmNGRmNTY0ODdhYTRjY2EyM2E2MTI0NTcwYmEwNzY6NjY2YzA0NDU5ODZhOQ%3D%3D&amp;ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OHxmMDkxYjFhNDU3NjFmY2ViNWE1MTZhYWJkMzA2NTE2NGI2MGVkYzUwfHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&amp;adtest=off&quot;,&quot;container&quot;:&quot;tc&quot;,&quot;styleId&quot;:7840396037,&quot;personalizedAds&quot;:false,&quot;channel&quot;:&quot;000001,bucket011,bucket077&quot;,&quot;domainName&quot;:&quot;vbaonline.in&quot;,&quot;fexp&quot;:&quot;21404,17301431,17301433,17301436,17301511,17301516,17301266&quot;,&quot;masterNumber&quot;:1,&quot;number&quot;:3,&quot;pubId&quot;:&quot;dp-mobile-teaminternet13_3ph&quot;,&quot;role&quot;:&quot;m&quot;,&quot;hl&quot;:&quot;en&quot;,&quot;client_gdprApplies&quot;:0,&quot;colorTitleLink&quot;:&quot;#0277bd&quot;,&quot;colorAttribution&quot;:&quot;#aaa&quot;,&quot;fontFamily&quot;:&quot;arial&quot;,&quot;fontFamilyAttribution&quot;:&quot;arial&quot;,&quot;rolloverLinkBold&quot;:false,&quot;rolloverLinkColor&quot;:&quot;#01579b&quot;,&quot;noTitleUnderline&quot;:false,&quot;lineHeightTitle&quot;:34,&quot;resultsPageBaseUrl&quot;:&quot;https://vbaonline.in/?ts=fENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OXxjNDk0NWE3YTZmYzJjMDgwNWJlZTEyODEzM2IxNzY4OTcxODQyYTE2fHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&quot;,&quot;columns&quot;:1,&quot;horizontalAlignment&quot;:&quot;center&quot;,&quot;resultsPageQueryParam&quot;:&quot;query&quot;,&quot;terms&quot;:&quot;&quot;,&quot;kw&quot;:&quot;&quot;,&quot;ie&quot;:&quot;UTF-8&quot;,&quot;maxTermLength&quot;:40,&quot;maxTop&quot;:null,&quot;minTop&quot;:null,&quot;oe&quot;:&quot;UTF-8&quot;,&quot;type&quot;:&quot;relatedsearch&quot;,&quot;linkTarget&quot;:&quot;_blank&quot;,&quot;verticalSpacing&quot;:10,&quot;fontSizeTitle&quot;:&quot;24px&quot;,&quot;fontSizeAttribution&quot;:&quot;14px&quot;,&quot;colorBackground&quot;:&quot;transparent&quot;,&quot;attributionBold&quot;:false,&quot;uiOptimize&quot;:true,&quot;domainRegistrant&quot;:&quot;as-drid-2558334540730768&quot;}}' and @id = 'master-1' and @src = 'https://syndicatedsearch.goog/afs/ads?adtest=off&amp;psid=7840396037&amp;pcsa=false&amp;channel=000001%2Cbucket011%2Cbucket077&amp;client=dp-mobile-teaminternet13_3ph&amp;r=m&amp;hl=en&amp;rpbu=https%3A%2F%2Fvbaonline.in%2F%3Fts%3DfENsZWFuUGVwcGVybWludEJsYWNrfHw1Y2U4NHxidWNrZXQwMTEsYnVja2V0MDc3fHx8fHx8NjY2YzA0NDU5ODY3NHx8fDE3MTgzNTUwMTMuNjQ5OXxjNDk0NWE3YTZmYzJjMDgwNWJlZTEyODEzM2IxNzY4OTcxODQyYTE2fHx8fHwxfHwwfDB8fHx8MXx8fHx8MHwwfHx8fHx8fHx8fDB8MHx8MHx8fDB8MHxXMTA9fHwxfFcxMD18ZWQwMjE1N2NjMDU1NzFiZTQ5MGZkNTc4NDAyN2ZhN2M5ZDMyMzZlNnwwfGRwLW1vYmlsZS10ZWFtaW50ZXJuZXQxM18zcGh8MHwwfHx8&amp;max_radlink_len=40&amp;type=3&amp;uiopt=true&amp;swp=as-drid-2558334540730768&amp;oe=UTF-8&amp;ie=UTF-8&amp;fexp=21404%2C17301431%2C17301433%2C17301436%2C17301511%2C17301516%2C17301266&amp;client_gdprApplies=0&amp;format=r3%7Cs&amp;nocache=9931718355015159&amp;num=0&amp;output=afd_ads&amp;domain_name=vbaonline.in&amp;v=3&amp;bsl=8&amp;pac=0&amp;u_his=2&amp;u_tz=330&amp;dt=1718355015160&amp;u_w=1920&amp;u_h=1080&amp;biw=929&amp;bih=873&amp;psw=929&amp;psh=791&amp;frm=0&amp;uio=--&amp;cont=tc&amp;drt=0&amp;jsid=caf&amp;nfp=1&amp;jsv=641883529&amp;rurl=https%3A%2F%2Fvbaonline.in%2F']</value>
      <webElementGuid>902a05aa-e2a0-45e2-b4a6-9e375821647e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
